### ISSUE TITLE
How to run video_player package on tvos? 

### ISSUE THREAD

**Issue by sidr16** [LibertyGlobal/flutter-tvos-demo#8]
### It gives this error on startup

I can't find a solution to this problem, can you help me to solve this problem?
```
2023-08-12 16:47:17.867753+0500 Runner[68192:636805] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: init() has not been implemented.
#0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43:5)
#1      _videoPlayerPlatform (package:video_player/video_player.dart:28:21)
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:426:25)
#3      _VideoPlayerScreenState.initPlayer (package:AppleTVTest/main.dart:226:33)
#4      _VideoPlayerScreenState.initState (package:AppleTVTest/main.dart:234:5)
```

**Comment by DenisovAV** [comment]
video_player plugin doesn't work with Apple TV, please take a look at this example https://github.com/denisovav/flutter_tv, I customized native_video_player there, and you can use it for video
